id: 5db25dbd-a6e9-46fc-a728-4697f677fbc6

slug: openai
title: OpenAI Observability

description: |
  ## Monitor your GPT-3 and GPT-4 Application Usage in New Relic

  With the GPT integration, you'll have the ability to seamlessly monitor OpenAI completion queries and simultaneously log useful statistics in a New Relic customizable dashboard about your requests.

  By adding just two lines of code, users can gain access to key performance metrics such as cost, response time, and sample inputs/outputs. The dashboard also allows users to track total requests, average token/requests, and model names. 

  With New Relic's fully customizable dashboard, users can add additional metrics based on their specific business requirements and needs. 

  Overall, New Relic's OpenAI integration provides real-time metrics around GPT applications to help businesses optimize usage, reduce costs, and achieve better results.

summary: |
  Seamlessly monitor your usage of OpenAI’s GPT Series APIs using New Relic’s dashboard. You'll get access to real-time metrics that can help you optimize usage, reduce costs, and achieve better results.

icon: openai-logo.svg

level: New Relic

authors:
  - New Relic
  - Yogev Kriger

documentation:
  - name: OpenAI integration using Python
    description: |
      Enhance the performance monitoring and instrumentation of your OpenAI by using the Python agent. 
    url: https://docs.newrelic.com/install/python
  - name: OpenAI integration using Node.js
    description: |
      Enhance the performance monitoring and instrumentation of your OpenAI by using the Node.js agent.
    url: https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/install-nodejs-agent

keywords:
  - generative-aillm
  - featured
  - openai
  - ai
  - gpt
  - llm
  - generative ai
  - chatgpt 
  - gpt 
  - chat 
  - genai
  - open

dataSourceIds:
  - llm-application
alertPolicies:
  - llm-application
