id: 5337037a-7822-438e-a89f-395b8920bad0
slug: apm-transaction-analysis
title: APM Transaction Analysis
description: |
  ## Why use this dashboard?
  Normally in the curated APM view you will see one application at a time.  When you have hundreds of applications and wish to analyze the relative performance accross apps, this view excels.
  Using the power of NRQL we present a unified drill down of performance that is very useful when setting up alert conditions and service levels.  It is very good at helping explore performance outliers.
summary: |
  A unified filterable view of transaction performance across an account.
level: New Relic
authors:
  - Jim Hagan
keywords:
  - APM
  - Transaction
  - NR1_addData
dataSourceIds:
  - solutions-hub-dashboards
documentation:
  - name: APM Transactions
    url: https://docs.newrelic.com/docs/apm/transactions/intro-transactions/transactions-new-relic-apm/
    description: Transactions in New Relic's APM
icon: logo.svg
website: https://www.newrelic.com
dashboards:
  - apm-transaction-analysis
