id: ec610a31-5374-47de-b8f7-ed240221412a
slug: audit-events-analysis
title: New Relic Audit
description: |
  Dashboard to analyse the New Relic Audit events that New Relic captures out of the box as an additional security measure for managing your New Relic account. This includes:

  - Individuals added or deleted
  - Role changes
  - Account changes made via API
  - Synthetic monitor changes
  - Dashboard deletion
  - Workload configuration changes

  All New Relic accounts can query up to 13 months of account changes. To ensure account security, the audit logging NRQL query only tracks changes in your currently selected account. It does not show audit log events for any associated child accounts. To query changes in another account or sub-account, select the account and run a NRQL query there.

  Audit logging is different than configuring audit mode for your APM agent. APM audit mode records information about all data being transmitted from your app.
summary: |
  Dashboard to analyse the New Relic Audit events
icon: logo.svg
level: New Relic
authors:
  - New Relic
  - Swati Joshi
keywords:
  - audit events
  - new relic
  - NR1_addData
  - NR1_sys
installPlans:
  - third-party-audit-events-analysis
dataSourceIds:
  - audit-events-analysis
documentation:
  - name: Query account audit logs
    url: https://docs.newrelic.com/docs/data-apis/understand-data/event-data/query-account-audit-logs-nrauditevent/
    description: |
      Additional information on the New Relic Audit events
dashboards:
  - audit
