id: bc77ddf0-fc12-41d0-9f35-e9cdc3061f2a
slug: boomi
title: Boomi
description: |+
  ## About Boomi

  Boomi helps you connect your applications, data, and people to accelerate your digital transformation.

  ### This Integration

  This integration will allow you to send traces from your Boomi environment to New Relic. Once set up, you can find the traces in the Boomi entity created from OpenTelemetry collector.

summary: Send traces from Boomi to New Relic using OpenTelemetry.
level: Verified
authors:
  - New Relic
  - Joseph Counts
keywords:
  - newrelic partner
  - boomi
  - apm
  - traces
  - NR1_addData
  - NR1_sys
dataSourceIds:
  - boomi
documentation:
  - name: Set up OTeL collector to monitor Boomi
    url: https://help.boomi.com/docs/atomsphere/flow/topics/flo-observability_collector_8b3010e3-51b1-43b5-8b09-9575e59610b0/#setting-up-the-apm-system-new-relic
    description: Docs for setting up an OpenTelemetry collector to send Traces from Boomi to New Relic
icon: logo.png
website: https://boomi.com/
